apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: service-b

configMapGenerator:
- literals:
  - NAME=service-b
  - PORT=8080
  - URL=http://service-c:8080
  name: service-b

resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml
images:
- name: brandonversus/service-x
  newName: brandonversus/service-x
  newTag: 1.0.20
