apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: service-a

configMapGenerator:
- literals:
  - NAME=service-a
  - PORT=8080
  - URL=http://service-b:8080
  name: service-a
  
resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml
images:
- name: brandonversus/service-x
  newName: brandonversus/service-x
  newTag: 1.0.20
